CREATE TABLE IF NOT EXISTS users
(
    id    INT PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    username VARCHAR(200) NOT NULL ,
    wallet INT  NOT NULL,
    access VARCHAR(20) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 2 INCREMENT BY 1;
--DROP TABLE IF EXISTS users;