CREATE TABLE IF NOT EXISTS users
(
    id    INT PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    username VARCHAR(200) NOT NULL ,
    wallet INT  NOT NULL,
    access VARCHAR(20) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 2 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS cars
(
    id    INT PRIMARY KEY ,
    model  VARCHAR(200) NOT NULL ,
    brand VARCHAR(200) NOT NULL ,
    price INT  NOT NULL,
    color VARCHAR(200) NOT NULL,
    year INT NOT NULL,
    max_speed INT NOT NULL,
    user_id INT NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE SEQUENCE IF NOT EXISTS cars_id_seq START WITH 1 INCREMENT BY 1;
--DROP TABLE IF EXISTS users;
